title: Milca Areli Sanchez Flor # your name (or website title) here
logo: "/images/mi_foto.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Architec, Data Developer, CABA, Argentina
  <br><br>
  "Mi objetivo es colaborar en el procesamiento de los datos que generamos diariamente, para desarrollar las soluciones m√°s innovadoras posible"
  <br><br> 
  
theme: jekyll-theme-minimal
